### PR TITLE
Adding HTTP request functionality 

### PR DESCRIPTION
**Pull request by funvill**
Adding in the HTTP request functionality that is described here 
http://www.abluestar.com/blog/geogramone-gps-tracker-to-google-maps/

Note: This is my first pull request. I may have made some errors in submitting it. I have done by best to double check it but you may wish to review it in more detail. 

Thanks for the awesome board.

### CODE REVIEW

**Comment by rjocoleman** [comment]
@DSSCircuits What do you think of this PR?

I'm about to start a GeogramONE based project to periodically HTTP POST to a HTTPS URL with the data either moving as `Content-Type: application/x-www-form-urlencoded` or `Content-Type: application/json`.

It strikes me that generic HTTP POST support would be beneficial and the output format could be documented so that users could implement their own receiving application (or use something like Zapier).

(I'll also be open-sourcing my receiving application with a basic UI)

I'm happy to take a crack at refactoring to achieve this sort of functionality - if there is interest?

I haven't spent too much time looking at the code yet but I'd look to set up something like:

```
#define USEHTTPPOST 1 //set to zero to free up code space if option is not needed
```

If space was a concern I could have SMS or HTTP as mutually exclusive options.

Alternatively I can present this as an alternative firmware with an exclusive focus on HTTP.

What do you think?

**Comment by DSSCircuits** [comment]
There have been a few inquiries into HTTP POST support, so yes I would be interested.  I'm in the process of large rewrite of the code and was able to free up about 2k of memory so I should have sufficient space. Unfortunately I don't have much experience with HTTP POST so I would also need to find a way to test the code.  Let me know what you come up with and I'll also start going through previous posts on the subject.

**Comment by rjocoleman** [comment]
Thanks @DSSCircuits. There are a number of pretty straightforward web services that will accept HTTP POST and display what's received in the browser,

e.g. http://requestb.in/

```
# POST to http://requestb.in/1ea1xa61
$ curl -X POST -d "fizz=buzz" http://requestb.in/1ea1xa61

# see it at http://requestb.in/1ea1xa61?inspect
```

Is your rewrite in a public branch? I can add the HTTP support and send a pull request against that.

My goal would be to add a HTTP related command, have some settings for this in EEPROM and have it configurable by SMS. 

Output would ideally be a [JSON payload](https://github.com/bblanchon/ArduinoJson):

``` json
{
    "dateTime": "",
    "latitude": "",
    "longitude": "",
    "speed": "",
    "course": "",
    "altitude": "",
    "hdop": "", 
    "vdop": "",
    "pdop": "",
    "satellitesUsed": "",
    "GSAModeTwo": "",
    "batteryPercent": "",
    "batteryVoltage": "",
    "rssi": ""
}
```

or a urlencoded form.

I'll knock up a basic receiving app first to demo/test received data.

**Comment by rjocoleman** [comment]
@DSSCircuits 

I knocked up a really basic app to accept this proposed input and show it back.

It's here: https://github.com/rjocoleman/mapper

It's also hosted on Heroku: https://sheltered-dusk-9230.herokuapp.com/

You can POST the JSON from my last comment to `https://sheltered-dusk-9230.herokuapp.com/pings/{token}` where `token` is any unique string.

If you visit  `https://sheltered-dusk-9230.herokuapp.com/pings/{token}` you'll see the results that have been sent.

e.g. I posted some junk data to `https://sheltered-dusk-9230.herokuapp.com/pings/foo` 
so you can see it at https://sheltered-dusk-9230.herokuapp.com/pings/foo

From here, with this app, it should be pretty straightforward to build in auth/privacy, format the output, plot the coordinates on a Google Map etc. 
Could also add in [twilio](https://www.twilio.com/) and SMS back the unit.. there are a bunch of possibilities.

(There's no validation so if you don't POST JSON in the schema above the app throw will error.)

DIY demo: 

```
curl -X "POST" "https://sheltered-dusk-9230.herokuapp.com/pings/bar" \
    -H "Content-Type: application/json" \
    -d $'{
    "dateTime": "one",
    "latitude": "two",
    "longitude": "three",
    "speed": "4",
    "course": "5",
    "altitude": "6",
    "hdop": "7",
    "vdop": "8",
    "pdop": "9",
    "satellitesUsed": "10",
    "food": "11",
    "batteryPercent": "12",
    "batteryVoltage": "14",
    "rssi": "13"
}'
```

https://sheltered-dusk-9230.herokuapp.com/pings/bar - this will be an error until the above command is run.

**Comment by momoteRyanmt** [comment]
:+1:  on this, the ability to push and pull data from the device would open up a lot of possibilities for web services. The JSON payload looks perfect

What about passing commands in the response body to trigger extra data / io switching + status and the likes to cutout the requirements for SMS as much?

Hopefully the Geogram gets HTTP support soon so I can start tinkering with web services.

**Pull request closed without merging**
